# Generated by Django 4.2.5 on 2023-09-12 06:51

from django.db import migrations

def create_data(apps, schema_editor):
    KufarVendor = apps.get_model('kufarVendor', 'KufarVendors')
    KufarVendor(name="Joe Silver", email="joe@email.com", prod_description="This text about something", phone="00000000", photo='media/photo/nophoto.png').save()
    KufarVendor(name="John Smith", email="john@email.com", prod_description="This text about something", phone="11111111", photo='media/photo/nophoto.png').save()
    KufarVendor(name="Alex Smith", email="alex@email.com", prod_description="This text about something", phone="22222222", photo='media/photo/nophoto.png').save()
    KufarVendor(name="Kira Night", email="kira@email.com", prod_description="This text about something", phone="33333333", photo='media/photo/nophoto.png').save()
    KufarVendor(name="Amanda Lex", email="amanda@email.com", prod_description="This text about something", phone="55555555", photo='media/photo/nophoto.png').save()
    KufarVendor(name="Oni Musha", email="oni@email.com", prod_description="This text about something", phone="44444444", photo='media/photo/nophoto.png').save()

class Migration(migrations.Migration):

    dependencies = [
        ('kufarVendor', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
