# Generated by Django 4.2.5 on 2023-09-11 09:35

from django.db import migrations

def create_data(apps, schema_editor):
    Kufar_prod = apps.get_model('kufar_prod', 'Kufar_prod')
    Kufar_prod(name="Joe Silver", email="joe@email.com", prod_description="This field for description somethink", phone="00000000",
            photo='media/photo/nophoto.png').save()
    Kufar_prod(name="John Smith", email="john@email.com", prod_description="This field for description somethink", phone="11111111",
            photo='media/photo/nophoto.png').save()
    Kufar_prod(name="Alex Smth", email="alex@email.com", prod_description="This field for description somethink", phone="22222222",
            photo='media/photo/nophoto.png').save()
    Kufar_prod(name="Kira Night", email="kira@email.com", prod_description="This field for description somethink", phone="33333333",
            photo='media/photo/nophoto.png').save()
    Kufar_prod(name="Amanda Lex", email="amanda@email.com", prod_description="This field for description somethink", phone="44444444",
            photo='media/photo/nophoto.png').save()
    Kufar_prod(name="Oni Musha", email="oni@email.com", prod_description="This field for description somethink", phone="44444444",
            photo='media/photo/nophoto.png').save()

class Migration(migrations.Migration):

    dependencies = [
        ('kufar_prod', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
